/*
 * Automatically generated by configure - do not modify
 * Configured with: * '/mnt/tmp/root/spack-stage/spack-stage-liburing-0.3-knbkmrgw5g42546yzijphsncaitfpvm6/spack-src/configure'
 */
#define CONFIG_HAVE_KERNEL_RWF_T
#define CONFIG_HAVE_KERNEL_TIMESPEC
