# Automatically generated by configure - do not modify
# Configured with: '/mnt/tmp/root/spack-stage/spack-stage-liburing-0.3-knbkmrgw5g42546yzijphsncaitfpvm6/spack-src/configure'
prefix=/usr
includedir=/usr/include
libdir=/usr/lib
mandir=/usr/man
datadir=/usr/share
CONFIG_HAVE_KERNEL_RWF_T=y
CONFIG_HAVE_KERNEL_TIMESPEC=y
